name: Build & deploy

on:
  push:
    branches: [next]
  pull_request:
    branches: [next]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: |
            lib
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          access: 'restricted'
          registry: https://npm.pkg.github.com